### ISSUE TITLE
Do not include bower_components in the repository

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/the-bouncy-castle#1]
Please remove the vendor scritps

**Comment by jerguslejko** [comment]
Also I just noticed that your project is missing `bower.json` file.

But you have commited the _bower_components_ directory so the workflow for solving this would be:

1. remove bower_components
2. `bower init`
3. `bower install jquery`
4. commit
5. `bower install`

**Comment by jerguslejko** [comment]
EDIT: `bower install --save jquery`

**Comment by matuskropuch** [comment]
resolved in 3ee49c8a55b08199ef67092a7fa2cea625027e24
