### ISSUE TITLE
Bouncy bounce - couldn't it be a super bouncy bouce?

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/the-bouncy-castle#3]
Just use an image without a background💃  💃

**Comment by matuskropuch** [comment]
resolved in 832ced74c5e7e7b9fd0cfbf805eb83407d3198f9

**Comment by jerguslejko** [comment]
the thing is...

the image you provided is approx 1100x1100 and you are resizing it with css to be ~300x300.

you should resize the image and use smaller as it is smaller therefore loads faster 🔵
