### ISSUE TITLE
Translate over simple calc?

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/the-bouncy-castle#4]
Although using `translate` property works in this example, it seems a bit heavy and unnecessary...

Please consider using

```
.class {
    left: calc(50% - 50px);
}
```
_50%_ represents a dimension (left -> width, top -> height) of the parent element.

Also, note that in order for the `top: calc(50% - 50px)` you need to set `html` and `body` to `height: 100%`:

```
html, body {
    height: 100%;
}
```

keep up the good work :)

**Comment by matuskropuch** [comment]
resolved in 022d01acd5337688e5737ce131fb00e9d5f36c06
