### ISSUE TITLE
Differentiate css classes and js classes

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/the-bouncy-castle#5]
It's a good practice to *not use* same css classes for styling and for js manipulation.

The convention works like this:

```html
<div class="dov js-dog">
</div>
```

```css
.dog {
    color: blue;
}
```

```js
$('.js-dog').doABarrelRoll();
```

Therefore you can change either css structure or js structure without breaking the other parts of your app.

keep up the good work :)

**Comment by matuskropuch** [comment]
resolved in 616320b00b44e1accbb4bfa2c3e36377c5cc5356
